logo: "/assets/images/search-station-logo.svg"
description: Standardized Documentation for Search Station Processes
theme: just-the-docs

url: https://marvinoka4.github.io/ss-documentation

aux_links:
  Template Repository: https://github.com/marvinoka4/ss-documentation
